README.md
pisces/urls.py
transformer/models.py
transformer/serializers.py
transformer/views.py

Adds additional API views and parameters:
- `source` and `object_type` parameters for `transform` endpoint
- adds a `find-by-id` endpoint
- adds a detail route for identifiers on Collections, Objects, Agents and Terms
- adds a route to create new identifiers associated with Collections, Objects, Agents and Terms

Additional API views

---

README.md
fixtures/cassettes/cartographer_fetch.yml
transformer/fetchers.py
transformer/test_library.py
transformer/tests.py
transformer/views.py

Handles deleted and unpublished data from Cartographer

---

transformer/mappings.py
transformer/mappings_helpers.py

This needs to be tested further, but sketches out a couple of ideas:
- Adds language mappings to `ArchivesSpaceResourceToCollection` which should take care of part of #131 
- Adds a helper function for fetching the closest value from a parent. This needs to be tested a bit more, but I think we could use this for dates as well.
Hillel

adds language mappings

---

transformer/mappings.py

Move the instantiation of asnake.ASpace to constructor method in mapping, fixes #136

Reduce number of AS API calls by moving ASnake instantiation to mapping class

---

transformer/resources.py

remove Ref

---

transformer/apps.py
transformer/mappings.py
transformer/mappings_helpers.py
transformer/resources.py
transformer/test_library.py
transformer/tests.py
transformer/transformers.py
transformer/views.py

Fixes #141 . Adds docstrings to code. Some strings may need some refinement, but they should cover most of the code.

Docstrings

---

transformer/tests.py

Adds tests to check values

---

transformer/mappings_helpers.py

Factors out common code from ArchivesSpaceHelper methods

---

fetcher/fetchers.py
fetcher/tests.py
fetcher/views.py
pisces/config.py.example
requirements.txt

Removes post service urls

---

fetcher/fetchers.py

Don't raise when fetchrun encounters exceptions

---

fetcher/tests.py
fixtures/cassettes/fetcher/Cartographer-deleted-arrangement_map.json
fixtures/cassettes/fetcher/Cartographer-updated-arrangement_map.json

Adds tests for Cartographer fetcher

---

.flake8

This was missing from linting PR earlier.

Adds flake8 config

---

fetcher/views.py
transformer/views.py

Uses Asterism `BaseServiceView` to provide the basics for views in fetchers and transformers.
fixes #195

Uses asterism view helpers, fixes #195

---

README.md
fetcher/models.py
fetcher/serializers.py

Also updates outdated routes listed in README
fixes #192

Adds error count to FetchRun, fixes #192

---

fetcher/fetchers.py
fetcher/helpers.py
pisces/config.py.example
transformer/transformers.py

Also improves exception handling generally speaking.
fixes #190

Saves error messages and URIs in FetchRunError objects

---

fixtures/cassettes/transformer/resources.json
fixtures/resources/397.json
requirements.txt
transformer/mappings.py

Handle different variations of `items` in subnotes

---

fetcher/helpers.py
transformer/transformers.py

Returns URIs in exceptions

---

fetcher/fetchers.py

Makes prefix checking more stringent

---

fixtures/cassettes/transformer/resources.json
fixtures/resources/12725.json
fixtures/resources/363.json
transformer/mappings.py

Improves handling for note titles and content

---

fetcher/models.py

Sorts FetchRunError objects by time created

---

transformer/transformers.py

Targets [ValidationError](https://python-jsonschema.readthedocs.io/en/stable/errors/#jsonschema.exceptions.ValidationError) exceptions and returns both the message and the path.
fixes #227

Returns meaningful messages from jsonschema validation

---

fixtures/cassettes/merger/archival_object-merge.json
merger/mergers.py

Adds merge logic for ancestors and children, and improves docstrings.
fixes #221 
fixes #222

Implements merge logic

---

fetcher/helpers.py
transformer/mappings.py

Refactoring to remove complexity

---

transformer/resources/rac.py
transformer/resources/source.py

Adds additional information to Resource docstrings.
fixes #241

Improving Resource docstrings

---

.gitmodules
requirements.txt
transformer/mappings.py
transformer/resources/rac.py
transformer/transformers.py
transformer/views.py

Addresses three interconnected issues:
- Replaces `rac-data-model` git submodule with `rac_schemas` library, fixes #240 
- Updates resources and mappings to handle distinction between list-like subnote items and text-like subnote content, fixes #246 
- Improves recursive removal of `$` keys, fixes #245

Updates mappings and validation

---

pisces/settings.py

Reduce page size in settings.py

---

fixtures/merger/archival_object/11440.json
fixtures/merger/archival_object/11441.json
fixtures/merger/archival_object/11442.json
fixtures/merger/resource/316.json
fixtures/merger/resource/93.json
fixtures/transformer/archival_object/11441.json
fixtures/transformer/archival_object/11442.json
fixtures/transformer/archival_object_collection/11440.json
fixtures/transformer/resource/316.json
fixtures/transformer/resource/93.json
merger/mergers.py
merger/tests.py
transformer/mappings.py
transformer/resources/source.py

Adds support for new `lang_materials` nested array in AS v2.7+ while retaining support for simpler `language` key in earlier versions. Thanks for nothing, ArchivesSpace.
fixes #198

Adds support for change of language to lang_materials in AS 2.7

---

merger/helpers.py
transformer/resources/source.py

Make indicator_2 and type_2 nullable fields

---

setup.cfg
transformer/static/css/styles.css

Makes long error messages visible in API UI

---

merger/helpers.py

Ensures that closests_creators always returns a list

---

transformer/resources/configs.py

Simplify INSTANCE_TYPES list

---

fetcher/fetchers.py
fetcher/helpers.py
merger/helpers.py

Adds flag to only instantiate repo if needed

---

fetcher/fetchers.py

Factors out object-specific logic in fetchers.
fixes #255

Isolates special handling needed for resources and archival_objects

---

fetcher/cron.py
fetcher/tests.py
fetcher/views.py
merger/tests.py
pisces/urls.py
transformer/transformers.py

Removes unused views and cleans up a bit.
fixes #270

Removes unused views

---

fetcher/views.py

Use list serializer for custom action endpoints
